{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vault.serviceAccountName" . }}
  labels:
{{ include "vault.labels" . | indent 4 }}
{{- end -}}
